### ISSUE TITLE
LocationAvailability not defined

### ISSUE THREAD

**Issue by freefri** [microg/android_external_GmsApi#3]
I've got the following exception running an app in my Nexus 4:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.location.LocationAvailability.isLocationAvailable()' on a null object reference`

I'm runing Android 6, in CM13 without Google Aps but with microG Services Core and Framework Proxy packages installed from the Fdroid repo (https://microg.org/fdroid/repo)

I was wondering if I need to install some other package. And where to find it.

I had a look to the following file that could be the provider I'm looking for https://github.com/microg/android_external_GmsApi/blob/master/play-services-api/src/main/java/com/google/android/gms/location/LocationAvailability.java 

Sorry if this is not the correct place to ask this. I would appreciate you can redirect me to correct place or give me a hint about what can I do to fix this exception.

**Comment by freefri** [comment]
This seems to be fixed in the last preview version 0.2.4-3-g47a61d6 https://microg.org/fdroid/repo/com.google.android.gms-9258262.apk

**Comment by ale5000-git** [comment]
In this commit: cf2927f275c53099781dbf965acb7c7f8ed36e97
